#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/ssap
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssapdev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssaptest
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        hbm2ddl:
          import_files: 'classpath:static-data.sql'

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace